export const CHORDS = {
  'Cmaj7': { type: 'open', frets: [-1, 3, 2, 0, 0, 0], notes: 'C E G B' },
  'C6': { type: 'open', frets: [-1, 3, 2, 2, 1, 3], notes: 'C E A G' },
  'Cmaj9': { type: 'open', frets: [-1, 3, 0, 0, 0, 0], notes: 'C D G B E' },
  'C7': { type: 'open', frets: [-1, 3, 2, 3, 1, 0], notes: 'C E Bb' },
  'Dm7': { type: 'open', frets: [-1, -1, 0, 2, 1, 1], notes: 'D A C F' },
  'D7': { type: 'open', frets: [-1, -1, 0, 2, 1, 2], notes: 'D A C F#' },
  'Dmaj7': { type: 'open', frets: [-1, -1, 0, 2, 2, 2], notes: 'D A C# F#' },
  'D6': { type: 'open', frets: [-1, -1, 0, 2, 0, 2], notes: 'D A B F#' },
  'Em7': { type: 'open', frets: [0, 2, 2, 0, 3, 0], notes: 'E B G D' },
  'E7': { type: 'open', frets: [0, 2, 0, 1, 0, 0], notes: 'E B D Ab' },
  'E6': { type: 'open', frets: [0, 2, 2, 1, 2, 0], notes: 'E B Ab C#' },
  'Em6': { type: 'open', frets: [0, 2, 2, 0, 2, 0], notes: 'E B G C#' },
  'Em9': { type: 'open', frets: [0, 2, 0, 0, 0, 2], notes: 'E B D G F#' },
  'E9': { type: 'open', frets: [0, 2, 0, 1, 0, 2], notes: 'E B D Ab F#' },
  'Fmaj7': { type: 'open', frets: [-1, -1, 3, 2, 1, 0], notes: 'F A C E' },
  'G7': { type: 'open', frets: [3, 2, 0, 0, 0, 1], notes: 'G B D F' },
  'Gmaj7': { type: 'open', frets: [3, 2, 0, 0, 0, 2], notes: 'G B D F#' },
  'G6': { type: 'open', frets: [3, 2, 0, 0, 0, 0], notes: 'G B D E' },
  'Am7': { type: 'open', frets: [-1, 0, 2, 0, 1, 0], notes: 'A E G C' },
  'A7': { type: 'open', frets: [-1, 0, 2, 0, 2, 0], notes: 'A E G C#' },
  'Amaj7': { type: 'open', frets: [-1, 0, 2, 1, 2, 0], notes: 'A E Ab C#' },
  'A6': { type: 'open', frets: [-1, 0, 2, 2, 2, 2], notes: 'A E C# F#' },
  'Am6': { type: 'open', frets: [-1, 0, 2, 2, 1, 2], notes: 'A E C F#' },
  'Bm7': { type: 'open', frets: [-1, 2, 0, 2, 0, 2], notes: 'B D A F#' },
  'Bm7b5': { type: 'open', frets: [-1, -1, 0, 2, 0, 1], notes: 'D A B F' },
  'Bbmaj7': { type: 'open', frets: [-1, 1, 3, 2, 3, -1], notes: 'Bb F A D' },
  'Cm7': { type: 'barre', frets: [-1, 3, 5, 3, 4, -1], notes: 'C G Bb Eb' },
  'Cm7b5': { type: 'barre', frets: [-1, 3, 4, 3, 4, -1], notes: 'C F# Bb Eb' },
  'Cm6': { type: 'barre', frets: [-1, 3, 5, 2, 4, -1], notes: 'C G A Eb' },
  'C#maj7': { type: 'barre', frets: [-1, 4, 6, 5, 6, -1], notes: 'C# Ab C F' },
  'C#7': { type: 'barre', frets: [-1, 4, 6, 4, 6, -1], notes: 'C# Ab B F' },
  'C#m7': { type: 'barre', frets: [-1, 4, 6, 4, 5, -1], notes: 'C# Ab B E' },
  'C#m7b5': { type: 'barre', frets: [-1, 4, 5, 4, 5, -1], notes: 'C# G B E' },
  'C#6': { type: 'barre', frets: [-1, 4, 6, 3, 6, -1], notes: 'C# Ab Bb F' },
  'C#m6': { type: 'barre', frets: [-1, 4, 6, 3, 5, -1], notes: 'C# Ab Bb E' },
  'Dm7b5': { type: 'barre', frets: [-1, 5, 6, 5, 6, -1], notes: 'D Ab C F' },
  'Dm6': { type: 'barre', frets: [-1, 5, 7, 4, 6, -1], notes: 'D A B F' },
  'Emaj7': { type: 'barre', frets: [0, -1, 1, 1, 0, -1], notes: 'E Eb Ab B' },
  'Em7b5': { type: 'barre', frets: [-1, 7, 8, 7, 8, -1], notes: 'E Bb D G' },
  'Ebmaj7': { type: 'barre', frets: [-1, 6, 8, 7, 8, -1], notes: 'Eb Bb D G' },
  'Eb7': { type: 'barre', frets: [-1, 6, 8, 6, 8, -1], notes: 'Eb Bb C# G' },
  'Ebm7': { type: 'barre', frets: [-1, 6, 8, 6, 7, -1], notes: 'Eb Bb C# F#' },
  'Ebm7b5': { type: 'barre', frets: [-1, 6, 7, 6, 7, -1], notes: 'Eb A C# F#' },
  'Eb6': { type: 'barre', frets: [-1, 6, 8, 5, 8, -1], notes: 'Eb Bb C G' },
  'Ebm6': { type: 'barre', frets: [-1, 6, 8, 5, 7, -1], notes: 'Eb Bb C F#' },
  'F7': { type: 'barre', frets: [1, -1, 1, 2, 1, -1], notes: 'F Eb A C' },
  'Fm7': { type: 'barre', frets: [1, -1, 1, 1, 1, -1], notes: 'F Eb Ab C' },
  'Fm7b5': { type: 'barre', frets: [-1, 8, 9, 8, 9, -1], notes: 'F B Eb Ab' },
  'F6': { type: 'barre', frets: [-1, 8, 10, 7, 10, -1], notes: 'F C D A' },
  'Fm6': { type: 'barre', frets: [-1, 8, 10, 7, 9, -1], notes: 'F C D Ab' },
  'F#maj7': { type: 'barre', frets: [2, -1, 3, 3, 2, -1], notes: 'F# F Bb C#' },
  'F#7': { type: 'barre', frets: [2, -1, 2, 3, 2, -1], notes: 'F# E Bb C#' },
  'F#m7': { type: 'barre', frets: [2, -1, 2, 2, 2, -1], notes: 'F# E A C#' },
  'F#m7b5': { type: 'barre', frets: [-1, 9, 10, 9, 10, -1], notes: 'F# C E A' },
  'F#6': { type: 'barre', frets: [-1, 9, 11, 8, 11, -1], notes: 'F# C# Eb Bb' },
  'F#m6': { type: 'barre', frets: [-1, 9, 11, 8, 10, -1], notes: 'F# C# Eb A' },
  'Gm7': { type: 'barre', frets: [3, -1, 3, 3, 3, -1], notes: 'G F Bb D' },
  'Gm6': { type: 'barre', frets: [-1, 10, 12, 9, 11, -1], notes: 'G D E Bb' },
  'Am7b5': { type: 'barre', frets: [-1, 0, 1, 0, 1, -1], notes: 'A Eb G C' },
  'Abmaj7': { type: 'barre', frets: [4, -1, 5, 5, 4, -1], notes: 'Ab G C Eb' },
};

export const HARMONY = {
  'C6':     ['Dm7', 'Em7', 'Am7', 'Fmaj7'],
  'Cmaj9':  ['Dm7', 'Em7', 'Am7', 'Fmaj7'],
  'D6':     ['Em7', 'G6', 'A7', 'Gmaj7'],
  'E6':     ['Amaj7', 'A6', 'F#m7', 'Em7'],
  'Em6':    ['Am7', 'Bm7', 'E7', 'A7'],
  'Em9':    ['Am7', 'A7', 'Cmaj7', 'Dm7'],
  'E9':     ['Am7', 'Amaj7', 'A6', 'Dm7'],
  'G6':     ['Cmaj7', 'Am7', 'Em7', 'D7'],
  'A6':     ['D6', 'Dmaj7', 'Em7', 'Bm7'],
  'Am6':    ['D7', 'Dm7', 'E7', 'Bm7b5'],
  'Bm7':    ['E7', 'Em7', 'Amaj7', 'A6'],
  'Cmaj7':  ['Dm7', 'Em7', 'Am7', 'Fmaj7'],
  'C7':     ['Fmaj7', 'Fm7', 'Gm7', 'Bbmaj7'],
  'Dm7':    ['G7', 'Gmaj7', 'Em7', 'Cmaj7'],
  'D7':     ['Gmaj7', 'Gm7', 'G7', 'Cmaj7'],
  'Dmaj7':  ['Em7', 'Am7', 'Bm7b5', 'Gmaj7'],
  'Em7':    ['Am7', 'A7', 'Dm7', 'Cmaj7'],
  'E7':     ['Am7', 'Amaj7', 'Dm7', 'Fmaj7'],
  'Fmaj7':  ['Bbmaj7', 'Em7', 'Dm7', 'Gm7'],
  'G7':     ['Cmaj7', 'Cm7', 'C7', 'Am7'],
  'Gmaj7':  ['Am7', 'Dm7', 'Em7', 'Cmaj7'],
  'Am7':    ['Dm7', 'D7', 'Em7', 'Fmaj7'],
  'A7':     ['Dm7', 'Dmaj7', 'Em7', 'Fmaj7'],
  'Amaj7':  ['Bm7b5', 'Em7', 'Dmaj7', 'Fmaj7'],
  'Bm7b5':  ['Em7', 'E7', 'Am7', 'Cmaj7'],
  'Bbmaj7': ['Cm7', 'Fmaj7', 'Gm7', 'Em7'],
  'Cm7':    ['F7', 'Fm7', 'Bbmaj7', 'Gm7'],
  'F7':     ['Bbmaj7', 'Cm7', 'Cmaj7', 'Gm7'],
  'Fm7':    ['Bbmaj7', 'Cm7', 'Fmaj7', 'Gm7'],
  'Gm7':    ['C7', 'Cmaj7', 'Cm7', 'F7'],
};
